apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: krishna-deploy
  name: krishna-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krishna-deploy
  template:
    metadata:
      labels:
        app: krishna-deploy
    spec:
      containers:
      - image: cloudsihmar/sandeep:19
        name: krishna-deploy
